function transFactors(seq) {
	const factors = {
		ATF6: /TGACGT/g,
		CREB: /TGACGCA/g,
		cMyc: /CACGTG/g,
		Gata1: /GATT/g,
		AhR: /TGCGTG/g
	};

	const trueFactors = {};
	const codes = Object.keys(factors);
	const vals = Object.keys(factors).map(function(key) {
		return factors[key];
	});

	for (let i = 0; i < vals.length; i += 1) {
		while ((match = vals[i].exec(seq)) !== null) {
			//       console.log("match found at " + match.index, match);
			if (!trueFactors[codes[i]]) {
				trueFactors[codes[i]] = [match.index + 1];
			} else {
				trueFactors[codes[i]].push(match.index + 1);
			}
		}
	}
	//   console.log(trueFactors)
	return trueFactors;
}

/* Test examples
Test.assertSimilar(transFactors(""), {});
Test.assertSimilar(transFactors("ACGT"), {});
Test.assertSimilar(transFactors("GATT"), { Gata1: [1] });
Test.assertSimilar(transFactors("TGACGTGACGT"), { ATF6: [1, 6] }); => FAILING TEST
Test.assertSimilar(transFactors("TGCGTGCGTG"), { AhR: [1, 5] }); = FAILING TEST
Test.assertSimilar(transFactors("CACGTGACGT"), { ATF6: [5], cMyc: [1] });
Test.assertSimilar(transFactors("ATGGCCGTCATGGCGCCCCGAACCCTCCTCCTGCTACTCTCGGGGGCCCTGGCCCTGACCCAGACCTGGGCGGGCTCCCACTCCATGAGGTATTTCTTCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAGGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTATTGGGACCAGGAGACACGGAATGTGAAGGCCC"), {});
Test.assertSimilar(transFactors("GATTCGGCGGACATGGCGGCTCAGATCACCAAGCGCAAGTGGGAGGCGGCCCATGAGGCGGAGCAGTTGAGAGCCTACCTGGATGGCACGTCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCACGGACCCCCCCAAGACACATATGACCCACCACCCCATCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACGGAGCTCGTGGAGACCAGGCCTGCAGGGGATGGAACCTTCCAGAAGTGGGCGGCTGTGGTGGTGCCTTCTGGAGAGGAGCAGAGATACACCTGCCATGTGCAGCATGAGGGTCTGCCCAAGCCCCTCACCCTGAGATGGGAGCTGTCTTCCCAGCCCACCATCCCCATCGTGGGCATCATTGCTGGCCTGGTTCTCCTTGGAGCTGTGATCACTGGAGCTGTGGTCGCTGCCGTGATGTGGAGGAGGAAGAGCTCAGATAGAAAAGGAGGGAGTTACACTCAGGCTGCAAGCAGTGACAGTGCCCAGGGCTCTGATGTGTCCCTCACAGCTTGTAAAGTGTGACACGTG"), { cMyc: [627], Gata1: [1] });
Test.assertSimilar(transFactors("GATTCGGCGGACATGGCGGCTCAGATCACCAAGCGCAAGTGGGAGGCGGCCCATGAGGCGGAGCAGTTGAGAGCCTACCTGGATGGCACGTGCGTGGAGTGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCACGGACCCCCCCAAGACACATATGACCCACCACCCCATCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACGGAGCTCGTGGAGACCAGGCCTGCAGGGGATGGAACCTTCCAGAAGTGGGCGGCTGTGGTGGTGCCTTCTGGAGAGGAGCAGAGATACACCTGCCATGTGCAGCATGAGGGTCTGCCCAAGCCCCTCACCCTGAGATGGGAGCTGTCTTCCCAGCCCACCATCCCCATCGTGGGCATCATTGCTGGCCTGGTTCTCCTTGGAGCTGTGATCACTGGAGCTGTGGTCGCTGCCGTGATGTGGAGGAGGAAGAGCTCAGATAGAAAAGGAGGGAGTTACACTCAGGCTGCAAGCAGTGACAGTGCCCAGGGCTCTGATGTGTCCCTCACAGCTTGTAAAGTGTGACACGTG"), { cMyc: [87, 628], Gata1: [1], AhR: [91] });
*/
